esphome:
  name: hlink-dev-espidf-switch

external_components:
  - source: components

logger:
  level: DEBUG

esp32:
  board: lolin_d32
  framework:
    type: esp-idf

uart:
  id: hitachi_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  parity: ODD

climate:
  - platform: hlink_ac
    name: "H-Link Test Climate Device"

switch:
  - platform: hlink_ac
    remote_lock:
      name: Remote lock